### PR TITLE
Added text

### PR DESCRIPTION
**Pull request by LarsTheHacker**
Added Start! and ending score displays.

### CODE REVIEW

**Review by indremak — CHANGES_REQUESTED** [review]
Button style needs adjusting when '...start!' is added. 
Missing Javascript implementation.

**Review by LarsTheHacker — COMMENTED** [review]
Sorry, I hadn't realized I had added the text to the button. I had wanted to add it as a title, so that the user would have a bit of time before starting to make sure their controls were ready. 
I'm still relatively new to JavaScript and HTML, so could I get some help trying to do this? When I was experimenting, I couldn't get the High Score and Your Score to display what I needed them to.
Any help is appreciated, and thanks for reviewing my changes. 👍 
-Lars

**Comment by indremak** [comment]
Maybe it would easier to do that game would not start automatically, only after New game button is clicked. 
If you want to do title 'start', I think you could do it similar as Game over text. Create new `div` element and change it's `display` property in Javascript.
If you want to change text with Javascript, you can select item in Javascript (set item Id in HTML, and use it to select item), and set it's innerHTML to variable or text that you want to be shown on UI.
If you have questions, I'm happy to help.

**Comment by Valdas3** [comment]
Closing due to inactivity.

**Pull request closed without merging**
