### PR TITLE
Change snake head

### LINKED ISSUE #8: Add a head to a snake
Make first cell of the snake different - to look like a head. You can style it like you want. You can also change style of the whole snake if you want.

### PR DESCRIPTION
**Pull request by madmaxWMFU**
Resolves #8 
Сan you look at this option?)

### CODE REVIEW

**Comment by indremak** [comment]
@madmaxWMFU Looks good :) Please resolve the conflicts so that I could merge it.

**Comment by madmaxWMFU** [comment]
@indremak please check my pull request 
IF all it is good mark it as 'hacktoberfest-accepted' and  'hacktoberfest', assignees issue/PR by me

**Review by indremak — CHANGES_REQUESTED** [review]
Previously snake head has different color, and now it isn't. Could you fix that?

**Comment by madmaxWMFU** [comment]
@indremak check please)

**Comment by indremak** [comment]
looks good :)

**Pull request merged**
