### PR TITLE
Add a button to let the user mute/unmute audio

### PR DESCRIPTION
**Pull request by albertodeago**
This PR enable the user to mute/unmute the audio of the game

### CODE REVIEW

**Comment by indremak** [comment]
Good job! 
Could you change text "audio" in the button to icons, which represents volume/playing sound and muted? I think it would look prettier. You can use icons from fontawesome.com or other icons that you like.

**Comment by albertodeago** [comment]
should be ok now :)
I added material font icons to do this

**Comment by indremak** [comment]
@albertodeago Could you solve conflicts that I could merge PR? 🙂

**Comment by albertodeago** [comment]
Is it ok like this?

**Pull request merged**
